import type { Metadata } from 'next';
import './globals.css';
import Provider from './provider';

export const metadata: Metadata = {
  title: 'Blog Post Synapsis',
  description: 'Generated by create next app',
};

import './globals.css';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body suppressHydrationWarning>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
