import type { Metadata } from 'next';
import './globals.css';
import Provider from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <body suppressHydrationWarning style={{ padding: 0, margin: 0 }}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
